{
 "title": "Videobridges",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "nodes",
    "label": "Videobridge",
    "query": "SHOW TAG VALUES ON \"jitsims_db\" FROM \"jvb-stats\" WITH KEY = \"node\""
   }
  ]
 },
 "panels": [
  { "title": "Conferences and Participants", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Conferences and Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "alias": "Conferences",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "conferences" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Participants",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "participants" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Conferences",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "Total Conferences Created",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_conferences_created" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Total Conferences Completed",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_conferences_completed" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$JvbUrl$/" }
     ]
    },
    {
     "alias": "Total Failed Conferences",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_failed_conferences" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$JvbUrl$/" }
     ]
    },
    {
     "alias": "Total Partially Failed Conferences",
     "measurement": "jvb-stats",
     "select": [
      [
       {
        "params": [
         "total_partially_failed_conferences"
        ],
        "type": "field"
       }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$JvbUrl$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Participants",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_participants" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  { "title": "Videobridge Statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Bit Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bps" }
   ],
   "targets": [
    {
     "alias": "Bit Rate Download",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "bit_rate_download" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Bit Rate Upload",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "bit_rate_upload" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Loss Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "alias": "Loss Rate Download",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "loss_rate_download" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Loss Rate Upload",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "loss_rate_upload" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Packet Rate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Packet Rate Download",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "packet_rate_download" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Packet Rate Upload",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "packet_rate_upload" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "url", "operator": "=~", "value": "/^$JvbUrl$/" }
     ]
    }
   ]
  },
  {
   "title": "RTT Aggregate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "RTT Aggregate",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "rtt_aggregate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Jitter Aggregate",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 12 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "Jitter Aggregate",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "jitter_aggregate" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "RTP Loss",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "RTP Loss",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "rtp_loss" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Bytes",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "alias": "Total Bytes Received",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_bytes_received" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    },
    {
     "alias": "Total Bytes Sent",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "total_bytes_sent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Channels",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Video Channels",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "videochannels" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Video Streams",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "Video Streams",
     "measurement": "jvb-stats",
     "select": [
      [
       { "params": [ "videostreams" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  { "title": "Host Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 22 } },
  {
   "title": "CPU Load",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Usage User",
     "measurement": "cpu",
     "select": [
      [
       { "params": [ "usage_user" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "cpu", "operator": "=", "value": "cpu-total" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Used Percent",
     "measurement": "mem",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 23 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "Used Percent",
     "measurement": "disk",
     "select": [
      [
       { "params": [ "used_percent" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "node", "operator": "=~", "value": "/^$nodes$/" },
      { "condition": "AND", "key": "path", "operator": "=", "value": "/" }
     ]
    }
   ]
  }
 ]
}