version: '3.2'

networks:
  jitsi-monitoring-stack:
    external: true

volumes:
  grafana_data:

services:

  grafana:
    image: grafana/grafana:7.0.3
    networks:
      jitsi-monitoring-stack:
        aliases:
          - grafana
    ports:
      - 3000:3000
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    environment:
      - "GF_SECURITY_ADMIN_PASSWORD=changeme"
    privileged: false
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"